function [ z ] = defaultLogging()
%DEFAULTLOGGING Summary of this function goes here
%   default logging state
z = struct('verbose',1, ... % can have multiple level (1 for main processing (logPlayer),2-submodule warnings, 3- submodule information)
    'plotting', 0, ...      % to control plotting results
    'dbgLogging', emptyDbgLogging, ...  % to store module specific data for debugging
    'unitTestLogging',emptyunitTestLogging); % to log module specific information for unit test
end

%function to control storing dbg info
function z = emptyDbgLogging()
z = struct('accCal',-1, ...
    'altitude', -1, ...
    'attitude', -1, ...
    'context', -1, ...
    'carryPos', -1, ...
    'dataBuffer', -1, ...
    'gyrCal', -1, ...
    'IGRFmodel', -1, ...
    'magCal', -1, ...    
    'pdrOutput', -1, ...
    'stepDetection', -1, ...
    'strideLength', -1, ...
    'walkingAngle', -1);
end

%function to control logging unit test related messages
function z = emptyunitTestLogging()
z = struct('accCal',-1, ...
    'altitude', -1, ...
    'attitude', -1, ...
    'context', -1, ...
    'carryPos', -1, ...
    'dataBuffer', -1, ...
    'gyrCal', -1, ...
    'IGRFmodel', -1, ...
    'magCal', -1, ...    
    'pdrOutput', -1, ...
    'stepDetection', -1, ...
    'strideLength', -1, ...
    'walkingAngle', -1, ...
    'memsControl', -1, ...
    'memsConfig', -1);
end
