function [ z ] = emptyStrideCalInfo()
%EMPTYACCCAL Summary of this function goes here
%   Detailed explanation goes here
z = struct('Dist_cm',       zeros(10,1),   ...
           'dTime',         zeros(10,1),   ...
           'Nsteps',        zeros(10,1),   ...
           'step_type',     zeros(10,1),   ...
           'f2_sum',        zeros(10,1),   ...
           'f_sum',         zeros(10,1),   ...
           'freq_std',      zeros(10,1),   ...
           'flag_buffer_upd',   0,         ...
           'CalInfo_buffer',    0);
end