function [ z ] = emptyStrideLength()
%   EMPTYACCCAL Summary of this function goes here
%   Detailed explaination goes here
z = struct('model',         strideLengthConsts.defaultStrideModel, ...
           'walkModel',     emptyStrideModel,   ...
           'runningModel',  emptyStrideModel,   ...
           'userInfo',      emptyUserInfo,      ...
           'strideCalInfo', emptyStrideCalInfo, ...
           'CalRef',        emptyCalRef,        ...
           'manual_input',  emptyManualInput,   ...
           'strideLength',  0,                  ...
           'checkIfreset',  0,                  ...
           'dbg',           emptyStrideDebug);
end


function [ z ] = emptyStrideModel()
z = struct('x0',            0,  ...     % constant
           'x',             0,  ...     % linear
           'x2',            0,  ...     % quadratic
           'minStride_cm',  0,  ...     % min stride for ths model
           'maxStride_cm',  0,  ...     % max Stride for this model
           'rSquare',       0);         % fitting of model with cal data
end

function [ z ] = emptyStrideDebug()
%EMPTYACCCAL Summary of this function goes here
%   Detailed explanation goes here
z = struct('');
end

function [ z ] = emptyManualInput()
%EMPTYACCCAL Summary of this function goes here
%   Detailed explanation goes here
z = struct('Dist_cm',       zeros(1,1),   ...
           'Time',          zeros(1,1),   ...
           'Nsteps',        zeros(1,1),   ...
           'flag',          zeros(1,1),   ...
           'activity',      zeros(1,1));
end

function [ z ] = emptyCalRef()
%   EMPTYACCCAL Summary of this function goes here
%   Detailed explaination goes here
z = struct('enable',         0,  ...
           'stepfreqSum',    0,  ...
           'stepfreq_2_Sum', 0,  ...
           'meanFreq',       0,  ...
           'stepStd',        0,  ...
           'f_elems',        0,  ... 
           'refDist_cm',     0,  ...
           'refStep',        0,  ...
           'refTime',        0,  ...
           'LastValidTime',  0,  ...
           'LastDistance',   0,  ...
           'LastValidStep',  0,  ...
           'UserID',         0,  ...
           'seg_dist',       0,  ... 
           'seg_time',       0,  ... 
           'seg_steps',      0,  ... 
           'Activity_curr',  0);
end






