function [ z ] = emptyStepFrequency()
%emptyStep Summary of this function goes here
%   Detailed explanation goes here
z = struct('value',                      0,      ...
            'currentValue',              0,      ...
            'confidence',                0,      ...
            'lastStepsIncluded',         0,      ...
            'lastStepFrequencyBuffer',   zeros(stepConsts.stepFrequencyMaxNoOfSteps,1), ...
            'lastStepDetected',          0,      ...
            'lastTimeConfidenceUpdated', 0);
end