function [ z ] = emptyStepResultsForState()
%emptyStep Summary of this function goes here
%   Detailed explanation goes here
data(stepConsts.stepResultBufferSize) = emptySteps;

z = struct('Time',          0,      ...
            'Norm',         0,      ...
            'Nsteps',       0,      ...
            'NHist',        0,      ...
            'NHistMax',     stepConsts.stepResultBufferSize, ...
            'bufferIndex',  0,      ...
            'steps',        data,   ...
            'ifWalking',    stepConsts.FALSE);
end