function z = emptyUnitTestResults()
%structure to hold unit test results
z = struct('accCal',emptyUnitTestStat, ...
    'altitude', emptyUnitTestStat, ...
    'attitude', emptyUnitTestStat, ...
    'context', emptyUnitTestStat, ...
    'dataBuffer', emptyUnitTestStat, ...
    'gyrCal', emptyUnitTestStat, ...
    'IGRFmodel', emptyUnitTestStat, ...
    'magCal', emptyUnitTestStat, ...
    'pdrOutput', emptyUnitTestStat, ...
    'stepDetection', emptyUnitTestStat, ...
    'strideLength', emptyUnitTestStat, ...
    'walkingAngle', emptyUnitTestStat, ...
    'memsControl', emptyUnitTestStat, ...
    'memsConfig', emptyUnitTestStat, ....
    'carryPos', emptyUnitTestStat);
end

function z = emptyUnitTestStat()
z = struct('Npass', 0, ...
    'Nfail', 0);
end