function [ s ] = emptyLocState
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
s = struct('Timestamp', 0, ...
    'Distance', 0, ...
    'Good_Data', 0, ...
    'OK_Data', 0, ...
    'Bad_Data', 0);
end

