function s = emptyOdoState()
%EMPTYODOSTATE Function constructing empty Odometer Point Object

s = struct('Speed', 0, ...
    'Heading', 0, ...
    'LON', 0, ...
    'LAT', 0, ...
    'GPS_LON', 0, ...
    'GPS_LAT', 0, ...
    'Time', 0, ...
    'Odo', 0, ...
    'Error', 0, ...
    'Error_meters', 0, ...
    'Good_Data', 0, ...
    'OK_Data', 0, ...
    'Bad_Data', 0, ...
    'Consecutive_Bad_Counter', 0, ...
    'Valid', 0);
end

