function memsState = memsLoader()
%function to create intial structure to hold all submodule state
memsState = emptyMemsState;
end

function z = emptyMemsState()
z = struct('logging', defaultLogging, ... %logging
    'control', defaultMemsControl, ... %control
    'info', emptyInfo, ... %sensor info
    'data', emptyDataBuffer, ... %data 
    'moduleState', emptyModuleState); %subfucntion
end

function z = emptyModuleState
isInit = 0;
z = struct('accCal',emptyAccCal(isInit), ...
    'altitude', emptyAltitude(isInit), ...
    'attitude', emptyAttitude(isInit), ...
    'context', emptyContext(isInit), ...
    'gyrCal', emptyGyrCal(isInit), ...
    'IGRFmodel', emptyIGRFmodel(isInit), ...
    'magCal', emptyMagCal(isInit), ...
    'pdrOutput', emptyPdrOutput(isInit), ...
    'stepDetection', emptyStepDetection(isInit), ...
    'carryPos', emptyCarryPos(isInit), ...
    'strideLength', emptyStrideLength(isInit), ...
    'walkingAngle', emptyWalkingAngle(isInit));
end

function z = emptyInfo
z = struct('phone',emptyPhoneInfo, ...
    'user', emptyUserInfo, ...
    'loc', emptyLocList);
end

function z = emptyLocList
z = struct('current',emptyPosInfo, ...
    'lastKnown', emptyPosInfo);
end