function z = emptyDataBuffer()
%emptyDataBuffer Summary of this function goes here
%Detailed explanation goes here
z = struct('acc', emptyDataFrame(3, 0, 0), ...
    'gyr', emptyDataFrame(3, 0, 0), ...
    'mag', emptyDataFrame(3,0, 0), ...
    'pressure', emptyDataFrame(1, 0, 0));
end